src/components/header/Header.tsx, src/main.tsx, src/utils/loadIpcRenderer.ts
현재 electron에서만 페이지 접속이 가능한 문제가 있어, 일반 웹 브라우저에서도 접속할 수 있게 변경
#3
=> ✨ 웹 브라우저에서도 접속 가능

src/utils/isTypes.ts
어떤 작업인가요?
작업 도중 타입이 명확하지 않을 때 사용 가능한  isTypes 개발
#9
=> isTypes Utils 개발

src/components/Typography/Bold.ts, src/components/Typography/Default.ts, src/components/Typography/Light.ts, src/components/Typography/Medium.ts, src/components/Typography/index.ts, src/components/header/Header.tsx, src/components/header/Search.tsx, src/components/index/HelloWorld.tsx, src/electron.ts
타이포그래피 컴포넌트 제작
#6
창 크기를 피그마와 동일하게 `1000x580`으로 변경하였습니다.
다 같이 창 크기에 이야기가 필요해보입니다
=> ✨ Typography 컴포넌트

package.json, src/constants/firebaseConfig.ts, src/main.tsx, yarn.lock
파이어베이스 설정
#8 
일단 적용은 되었는데 추가적으로 더 설정할 부분이 있을지는 잘 모르겠네요
=> 🔧 파이어베이스 설정

src/components/header/Header.tsx
=> 💄 헤더 간격 수정

src/components/artists/Artist.tsx, src/components/artists/Tab.tsx, src/components/gnb/GNB.tsx, src/constants/dummys.ts, src/main.tsx, src/pages/artists/Artists.tsx
=> ✨ 아티스트 페이지

src/components/globals/musicControllers/musicControllerContainers/MusicControllerBar.tsx, src/components/globals/musicControllers/musicControllerContainers/MusicControllerPlayer.tsx, src/pages/chart/Chart.tsx
어떤 작업인가요?
앱바 작업
#42
- 플레이어 용 앱바 작업
- 기본 pc화면 용 앱바 잡업
=> ♻️ : MusicController 완성

src/utils/formatting.ts
=> 🐛 formatNumber 함수의 오류 수정

.gitignore, package.json, src/apis/index.ts, src/components/chart/MusicList.tsx, src/main.tsx, yarn.lock
api 세팅
생각나는 세팅이 이거 밖에 없더라고요 먼가먼가 빼먹은거 같은...?
#38
- instance 세팅
=> 🔨 : api 세팅

src/components/player/Visual/LyricsMode.tsx
=> 💄 진짜 진짜 마진 수정

src/apis/index.ts, src/utils/staticUtill.ts, vite.config.ts
Vite에서 제공하는 env로 교체
https://ko.vitejs.dev/guide/env-and-mode.html
- Vite env로 교체
=> 🐛 Vite에서 제공하는 env로 교체

src/components/header/Search.tsx, src/components/modals/CreateListModal/index.tsx, src/components/modals/LoadListModal/index.tsx, src/components/player/Controller.tsx, src/hooks/createListModal.ts, src/hooks/loadListModal.ts, src/hooks/player.ts, src/state/player/atoms.ts
스페이스바로 노래를 멈추거나 재생할 수 있도록 했습니다
- 스페이스바로 노래를 멈추거나 재생할 수 있도록 했습니다
=> :sparkles: 스페이스 바로 노래 틀고 끄기

src/apis/artist/index.ts, src/apis/charts/index.ts, src/apis/playlist/index.ts, src/apis/songs/index.ts, src/components/globals/UpdatedText.tsx, src/components/index/Chart.tsx, src/components/index/RecommendItem.tsx, src/main.tsx, src/pages/artists/Artist.tsx, src/pages/chart/Chart.tsx, src/pages/index/Index.tsx, src/pages/search/Search.tsx, src/pages/user/Playlist.tsx, src/templates/playlist.ts, src/templates/song.ts, src/utils/staticUtill.ts
몇몇 페이지 api 작업
(#80 에서 일부 코드 돚거함)
#85
- 메인 페이지의 왁뮤차트 API 연결
- 추천 플레이리스트 API 연결
- 왁뮤차트 API 연결
- 검색 페이지 API 연결
=> 몇몇 페이지 api 작업

src/components/index/RecommendItem.tsx, src/pages/index/Index.tsx, src/utils/listChunk.ts
추천 아이템들을 8개씩 분리하고 탭 간 애니메이션을 구현하였습니다.
- 추천 아이템 8개씩 분리
- 탭 간 움직임 구현
=> 💫 추천 아이템 애니메이션 구현

src/components/globals/Marquee.tsx, src/components/globals/SongItem.tsx, src/components/globals/Track.tsx, src/components/player/Default/Song.tsx, src/components/player/Visual/LyricsMode.tsx, src/components/search/tabs/All.tsx
긴 텍스트가 움직이게
#95
- Marquee 컴포넌트 제작
- Track 컴포넌트와 플레이어에 적용
- 검색 페이지 코드 구조 살짝 변경
=> ✨ 흘러가는 텍스트 구현

src/apis/artist/index.ts, src/components/artists/ArtistImage.tsx, src/components/artists/ArtistInfo.tsx, src/templates/artists.ts, src/utils/staticUtill.ts
새로운 아티스트 API 적용
#104 
- 새로운 아티스트 API 적용
=> 👽️ 새로운 아티스트 API

src/components/gnb/GNB.tsx, src/components/gnb/User.tsx, src/components/modals/ConfirmModal.tsx, src/components/modals/LoginModal/Button.tsx, src/components/modals/LoginModal/index.tsx, src/components/modals/SelectProfileModal/ProfileButton.tsx, src/constants/platforms.ts, src/hooks/user.ts, src/pages/mypage/MyPage.tsx, src/state/user/atoms.ts, src/templates/user.ts, src/utils/staticUtill.ts
유저 state 구현
- #103
- GNB에서 '로그인 하기', '로그아웃', 프로필 버튼 구현
- `userState` 제작
=> ✨ 유저 state

src/components/search/tabs/All.tsx
검색에서 어떤 탭의 노래 개수가 0 이여도 표시, 탭의 곡이 4개 이상일 시에만 전체보기 버튼 활성화
- #112
=> ✨ 검색에서 어떤 탭의 결과가 0이여도 표시

src/electron.ts, src/electron/discord.ts
디스코드 RPC reconnect 구현
- #83 
- 디스코드 RPC reconnect 구현
=> ✨ 디스코드 RPC reconnect 구현

src/apis/lyrics/index.ts, src/components/gnb/GNB.tsx, src/components/modals/AddListModal/index.tsx, src/components/modals/CreateListModal/index.tsx, src/components/modals/globals/BaseInput.tsx, src/components/modals/globals/ListNameInput.tsx, src/components/search/tabs/All.tsx, src/hooks/addListModal.ts, src/main.tsx, src/state/addListModal/atoms.ts, src/templates/image.ts, src/templates/playlist.ts, src/utils/staticUtill.ts
'보관함에 담기' 모달 제작
- #113
- '보관함에 담기' 모달
- 리스트 만들기 모달에서 쓰이던 인풋 컴포넌트를 ListNameInput 로 리팩토링
=> ✨ 보관함에 담기 모달

src/components/globals/ControlBar.tsx, src/components/gnb/User.tsx, src/constants/ipc.ts, src/electron.ts, src/electron/scheme.ts, src/electron/tray.ts, src/pages/mypage/MyPage.tsx, src/state/player/atoms.ts, src/utils/checkPlayerMode.ts, src/utils/schemeHandler.ts, vite.main.config.ts
트레이와 백그라운드 재생
- #123
- 트레이 시스템 제작
- 창 닫고 백그라운드에서 재생하는 시스템
=> ✨ 트레이와 백그라운드 재생

.github/workflows/check.yml, package.json, src/components/header/Search.tsx, src/components/player/Lyrics.tsx, src/components/player/Volume.tsx, src/constants/dummys.ts, src/pages/user/Mylist.tsx, src/utils/schemeHandler.ts, src/utils/staticUtill.ts
코드 체크 깃허브 액션
- eslint 린팅, tsc 린팅 액션 설정
- 오류나는 것들 임시로 처리
=> 👷 코드 체크 깃허브 액션

src/player/providers/YouTube.tsx, src/state/player/atoms.ts
볼륨 버그 수정
- 유튜브 노멀라이징을 포기하여서 안정적인 볼륨 조절 구현
- 로컬스토리지에 볼륨 저장에 throttle 적용하여서 최적화
=> 🐛 볼륨 버그 수정

src/apis/playlist/index.ts, src/apis/user/index.ts, src/components/globals/musicControllers/MusicController.tsx, src/components/modals/AddListModal/index.tsx, src/components/modals/ConfirmModal.tsx, src/components/modals/CreateListModal/index.tsx, src/components/user/mylist/MylistItem.tsx, src/constants/dummys.ts, src/hooks/addListModal.ts, src/hooks/createListModal.ts, src/hooks/player.ts, src/hooks/playlist.ts, src/pages/user/Likes.tsx, src/pages/user/Mylist.tsx, src/pages/user/Playlist.tsx, src/player/PlayerService.tsx, src/player/providers/YouTube.tsx, src/state/addListModal/atoms.ts, src/state/createListModal/atoms.ts, src/state/playlist/atoms.ts, src/state/user/atoms.ts, src/templates/playlist.ts, src/utils/staticUtill.ts, src/utils/utils.ts
플레이리스트 api 작업
- #110 
- 일부 유튜브 플레이어 버그 수정
- 플레이리스트 API 작업
- 리스트 생성
- 리스트 가져오기
- 리스트 순서 편집
- 리스트에 담기
- 리스트 상세
- 리스트 재생
- _**기존 리스트 관련 코드가 매우 더러워서 일단 api 작업(지금 이거) 마치고 @sandsunset이 리팩토링 해야함**_
- 스켈레톤 작업
- 토스트 메시지
- 개발 중 발견한 이슈들 처리
- #162
- #163
=> 플레이리스트 api 작업

package.json, src/index.html, src/main.tsx, vite.renderer.config.ts, yarn.lock
애널리틱스 설정
- Microsoft Clarity 셋업
- Firebase 라이브러리 드롭
- 직접 GA4 설정
=> ✨ 애널리틱스 설정

build/licenseTemplate.html, package.json, src/constants/myPage.tsx, vite.renderer.config.ts, yarn.lock
오픈소스 라이선스 HTML 생성
- #108
- 오픈소스 라이선스 HTML 생성
=> 오픈소스 라이선스 HTML 생성

src/components/globals/CustomSongs.tsx
CostomSongs children 동기화 버그 해결
- CostomSongs children 동기화 버그를 해결했습니다
=> 🐛 CustomSongs children 동기화 버그

src/components/gnb/User.tsx
=> 🐛 p 태그 안에 p 태그가 있으면 안됨

src/components/globals/Skeleton.tsx
빤짝거리는 애니메이션 적용한 더 나은 스켈레톤 디자인
https://discord.com/channels/979764222424657930/1026538397302521866/1146412929802059777
=> ✨ 더 나은 스켈레톤 디자인

src/apis/lyrics/index.ts, src/electron/discord.ts, src/player/PlayerService.tsx, src/player/providers/YouTube.tsx
몇 가지 작은 수정
- 이상하게 작동하던 디스코드 RPC 수정
- 볼륨을 200%로 설정
- 가사 로딩 최적화
=> 몇 가지 작은 수정

src/components/playlist/Header.tsx, src/components/user/mylist/MylistItem.tsx, src/pages/user/Mylist.tsx, src/pages/user/Playlist.tsx
=> ✨ 내 리스트 & 추천 플리 스켈레톤 작업

src/components/player/Default/Playlist.tsx, src/components/player/Default/Song.tsx, src/components/player/Like.tsx, src/components/player/Timeline.tsx, src/components/player/View.tsx, src/components/player/Visual/DefaultMode.tsx, src/components/player/Visual/Header.tsx, src/components/player/Visual/Visual.tsx
플레이어의 몇가지 버그 픽스
- #180 
- #184 
- 비주얼모드 타임라인에 호버하면 마진이 이상해지는 버그 수정
- 플레이어 플레이리스트에서 곡을 맨 아래로 스크롤하면 커서가 0으로 이동되는 버그 수정
- 비주얼모드 줌 상태에서 타임라인 드래그 컨트롤이 이상하던 버그 수정
- 좋아요 수 호버로 표시
=> 플레이어 마이너 픽스

src/main.tsx, src/player/PlayerService.tsx, src/utils/consoleApi.ts
=> 언제부턴가 사라져있던 콘솔 api 되돌리기

src/electron.ts
=> ✨ 프로그램 시작 시 줌 리셋

src/electron.ts, src/electron/tray.ts, src/utils/schemeHandler.ts
=> ✨ 트레이에 일시정지 버튼

src/components/globals/SongItem.tsx
=> ✨ SongItem hover시 bg 변경

src/components/modals/AddListModal/index.tsx
딤 클릭으로 노래 담기 모달이 안 꺼지던 문제 픽스
- #177
=> 🐛 딤 클릭으로 노래 담기 모달이 안 꺼지던 문제 픽스

src/components/gnb/Section.tsx, src/pages/user/User.tsx
로그인하지 않은 상태로 보관함에 들어가면 로그인 모달 띄우기
- #179
=> ✨ 로그인하지 않은 상태로 보관함에 들어가면 로그인 모달 띄우기

src/state/player/atoms.ts
=> 🐛 볼륨 저장 안되는 버그

src/App.tsx, src/layouts/ErrorLayout.tsx, src/main.tsx, src/pages/NotFound/NotFound.tsx
404 페이지와 오류 페이지 제작
- 404 페이지
- 오류 페이지
- main.tsx에서 App.tsx 분리
=> ✨ 404 페이지와 오류 페이지

src/App.tsx, src/components/globals/ControlBar.tsx, src/components/gnb/User.tsx, src/components/modals/ExitModal.tsx, src/constants/ipc.ts, src/electron.ts, src/hooks/exitModal.ts, src/state/exitModal/atoms.ts
프로그램 완전 종료 / 백그라운드로 최소화 선택 가능하게 제작
=> 어떻게 종료할지 선택

src/apis/lyrics/index.ts
=> ✨ 가사 시간에 0.3초 더하기

src/components/player/Volume.tsx
=> ✨ 볼륨 인디케이터

src/components/player/Default/Playlist.tsx
=> ✨ 플레이어 재생목록 호버 색 변경

src/components/faq/Section.tsx, src/pages/faq/Faq.tsx
faq 역순, 짤림 버그 수정
- #214 
- #217
=> 🐛 faq 역순, 짤림 버그 수정

src/electron.ts
앱이 백그라운드 모드로 hide 된 상태일 때 다시 프로그램 exe를 눌러 실행시 show하기
- #218
=> 🐛 백그라운드 상태에서 프로그램 실행시 restore

src/components/player/Default/Display.tsx
분리모드에서 플레이어 재생목록 버튼 누르면 기본모드로 전환
- #212
=> 🐛 분리모드에서 재생목록 누르면 기본모드로 전환

src/components/globals/ControlBar.tsx
=> 🐛 비주얼모드에서 최대화 버튼 작동하게

src/components/globals/musicControllers/MusicController.tsx, src/components/player/Default/Playlist.tsx, src/hooks/player.ts, src/state/player/atoms.ts, src/templates/player.ts
=> ✨ 플레이리스트 곡 중복 방지

src/components/player/Lyrics.tsx, src/components/player/Timeline.tsx, src/components/player/Visual/Visual.tsx, src/state/player/atoms.ts
플레이어 몇가지 수정
- ✨ 전주 때 가사를 하이라이트하지 않음
- 🐛 visual 컴포넌트의 resizeObserver 작동하지 않던 오류 해결
- 🐛 최초 재생 시에 타임라인이 너무 길어져버리는 오류 해결
=> 플레이어 몇가지 수정

forge.config.ts
dmg 창이 비정상적으로 크게 나오는 현상을 수정하였습니다.
=> :bug: change dmg height

src/components/search/tabs/All.tsx, src/components/user/mylist/ListController.tsx, src/pages/user/Mylist.tsx
내 리스트 드래그 버그 수정
은 아니였지만 수정하다보니 갑자기 작동함
- #244
- 내 리스트 드래그에서 mouse 이벤트의 주체를 div에서 window로 바꿈
=> 🐛 내 리스트 드래그 버그 수정

src/components/globals/Track.tsx
썸네일을 클릭해야만 노래 재생 가능하게 수정
(기존. 노래 텍스트도 재생 클릭 가능 범위였음)
=> 🐛 썸네일로만 재생 가능

src/components/player/Default/Playlist.tsx
`player/Default/Playlist.tsx`에서 
현재 재생 곡 정보 저장을 위해 index를 사용하던 코드를
모두 songId를 사용하는 방식으로 변경했습니다
=> 🎨 index 대신 songId로 비교하는 구조로 변경

src/App.tsx, src/components/globals/ControlBar.tsx, src/components/modals/AddListModal/index.tsx, src/components/modals/ExitModal.tsx, src/components/modals/globals/TwoButton.tsx, src/electron.ts
분리모드에서 닫기 선택 팝업
- selectExit 라우트 추가
- `WINDOW_CLOSE`, `WINDOW_HIDE` 이벤트의 대상을 모든 창으로 변경
=> ✨ 분리모드에서 닫기 선택 팝업

src/hooks/selectSongs.ts
shift로 여러 노래 한번에 선택
#257 
- shift로 여러 노래 한꺼번에 선택하기
나중에 @choshinyoung 님이 플레이어 쪽에서 겹치는 코드를 제거해주셔야 함
=> :sparkles: Shift로 다중선택

src/components/index/Chart.tsx
홈에서 '왁뮤차트 TOP100' 클릭시 왁뮤차트로 이동
=> ✨ 홈에서 '왁뮤차트 TOP100' 클릭시 왁뮤차트로 이동

src/utils/schemeHandler.ts
=> 🐛 로그인시 likes fetch하기

src/components/globals/musicControllers/MusicController.tsx
비로그인 상태에서 노래담기를 누르면...
- 기본 모드: 로그인 모달 뜸
- 분리 모드: 노래담기 버튼이 없어짐
- #251
=> 🐛 비로그인 상태에서 노래담기 대응

src/components/globals/CustomSongs.tsx, src/components/globals/SongItem.tsx, src/components/player/Default/Playlist.tsx, src/hooks/selectSongs.ts
selectSongs의 shift select구조 수정
=> 🎨 selectSongs의 shift select구조 수정

src/components/player/Default/Shortcuts.tsx
=> 🐛 의도되지 않은 키 입력 제한

src/components/player/Lyrics.tsx
✨ 마지막 가사가 끝난 후에 가사를 하이라이트하지 않음
=> ✨ 마지막 가사가 끝난 후에 가사를 하이라이트하지 않음

src/components/player/Default/Playlist.tsx
곡을 재생하면 플레이어 플레이리스트에서 해당 곡의 위치로 자동 스크롤되게 하기
=> ✨ 곡을 재생하면 해당 곡으로 스크롤

src/components/globals/musicControllers/MusicController.tsx, src/components/modals/AddListModal/index.tsx
더 나은 노래담기 메시지
- #268
- 취소하였습니다 제거
- 중복 곡 담기 처리
=> ✨ 더 나은 노래담기 메시지

src/hooks/likes.ts
=> ✨ 좋아요 수를 실시간으로 반영해서 보여주기

src/components/player/Default/Song.tsx, src/components/player/Timeline.tsx, src/components/player/Visual/DefaultMode.tsx, src/components/player/Visual/LyricsMode.tsx, src/components/player/Volume.tsx
플레이어 버그 픽스
- 🎨 타임라인 호버 범위 수정
- 🐛 마우스를 빠르게 이동시키면 볼륨 호버가 해제되지 않는 버그 픽스
=> 플레이어 버그 픽스

src/components/player/View.tsx, src/hooks/likes.ts, src/utils/formatting.ts
🐛 song이 null일 때 플레이어 like, view 대응
=> 🐛 song이 null일 때 플레이어 like, view 대응

src/hooks/player.ts, src/player/providers/YouTube.tsx
유튜브 조회수 반영하도록 패치
api로 재생하는 것이 아닌 iframe에 있는 재생버튼을 누르도록 수정
=> ✨ 유튜브 조회수 반영하도록 패치

src/App.tsx, src/components/globals/ControlBar.tsx, src/components/header/Header.tsx, src/components/index/Splash.tsx, src/components/modals/UpdateModal.tsx, src/components/player/Visual/Header.tsx, src/constants/ipc.ts, src/electron.ts, src/electron/tray.ts, src/hooks/modal.ts, src/state/modal/atoms.ts
맥 신호등 버튼 버그 수정
- 맥 신호등 버튼 버그 수정
- 윈도우 비주얼 모드에서 실종된 컨트롤바 복구
=> :bug: 맥 신호등 버튼

README.md, build/appx/manifest.xml, package.json, src/components/globals/ControlBar.tsx, src/components/player/Default/Display.tsx, src/components/player/Default/Shortcuts.tsx, src/constants/ipc.ts, src/electron.ts, src/hooks/toggleSeparateMode.ts
미니모드 & 1.1.0
- 미니모드 제작
- 버전 1.1.0로 업
=> ✨ 미니모드 & 1.1.0
